<?xml version="1.0" encoding="UTF-8" ?>
<Package name="pepper_cocorobo" format_version="4">
    <Manifest src="manifest.xml" />
    <BehaviorDescriptions>
        <BehaviorDescription name="behavior" src="behavior_1" xar="behavior.xar" />
    </BehaviorDescriptions>
    <Dialogs />
    <Resources>
        <File name="AUTHORS" src="lib/pycurl/AUTHORS" />
        <File name="ChangeLog" src="lib/pycurl/ChangeLog" />
        <File name="COPYING-LGPL" src="lib/pycurl/COPYING-LGPL" />
        <File name="COPYING-MIT" src="lib/pycurl/COPYING-MIT" />
        <File name="INSTALL" src="lib/pycurl/INSTALL.rst" />
        <File name="Makefile" src="lib/pycurl/Makefile" />
        <File name="MANIFEST" src="lib/pycurl/MANIFEST.in" />
        <File name="PKG-INFO" src="lib/pycurl/PKG-INFO" />
        <File name="README" src="lib/pycurl/README.rst" />
        <File name="RELEASE-NOTES" src="lib/pycurl/RELEASE-NOTES.rst" />
        <File name="requirements-dev-2.4" src="lib/pycurl/requirements-dev-2.4.txt" />
        <File name="requirements-dev-2.5" src="lib/pycurl/requirements-dev-2.5.txt" />
        <File name="requirements-dev" src="lib/pycurl/requirements-dev.txt" />
        <File name="setup" src="lib/pycurl/setup.py" />
        <File name="winbuild" src="lib/pycurl/winbuild.py" />
        <File name="callbacks" src="lib/pycurl/doc/callbacks.rst" />
        <File name="conf" src="lib/pycurl/doc/conf.py" />
        <File name="curl" src="lib/pycurl/doc/curl.rst" />
        <File name="curlmultiobject" src="lib/pycurl/doc/curlmultiobject.rst" />
        <File name="curlobject" src="lib/pycurl/doc/curlobject.rst" />
        <File name="curlshareobject" src="lib/pycurl/doc/curlshareobject.rst" />
        <File name="files" src="lib/pycurl/doc/files.rst" />
        <File name="index" src="lib/pycurl/doc/index.rst" />
        <File name="install" src="lib/pycurl/doc/install.rst" />
        <File name="internals" src="lib/pycurl/doc/internals.rst" />
        <File name="pycurl" src="lib/pycurl/doc/pycurl.rst" />
        <File name="quickstart" src="lib/pycurl/doc/quickstart.rst" />
        <File name="release-notes" src="lib/pycurl/doc/release-notes.rst" />
        <File name="release-process" src="lib/pycurl/doc/release-process.rst" />
        <File name="unicode" src="lib/pycurl/doc/unicode.rst" />
        <File name="curl" src="lib/pycurl/doc/docstrings/curl.rst" />
        <File name="curl_close" src="lib/pycurl/doc/docstrings/curl_close.rst" />
        <File name="curl_errstr" src="lib/pycurl/doc/docstrings/curl_errstr.rst" />
        <File name="curl_getinfo" src="lib/pycurl/doc/docstrings/curl_getinfo.rst" />
        <File name="curl_pause" src="lib/pycurl/doc/docstrings/curl_pause.rst" />
        <File name="curl_perform" src="lib/pycurl/doc/docstrings/curl_perform.rst" />
        <File name="curl_reset" src="lib/pycurl/doc/docstrings/curl_reset.rst" />
        <File name="curl_setopt" src="lib/pycurl/doc/docstrings/curl_setopt.rst" />
        <File name="curl_unsetopt" src="lib/pycurl/doc/docstrings/curl_unsetopt.rst" />
        <File name="multi" src="lib/pycurl/doc/docstrings/multi.rst" />
        <File name="multi_add_handle" src="lib/pycurl/doc/docstrings/multi_add_handle.rst" />
        <File name="multi_close" src="lib/pycurl/doc/docstrings/multi_close.rst" />
        <File name="multi_fdset" src="lib/pycurl/doc/docstrings/multi_fdset.rst" />
        <File name="multi_info_read" src="lib/pycurl/doc/docstrings/multi_info_read.rst" />
        <File name="multi_perform" src="lib/pycurl/doc/docstrings/multi_perform.rst" />
        <File name="multi_remove_handle" src="lib/pycurl/doc/docstrings/multi_remove_handle.rst" />
        <File name="multi_select" src="lib/pycurl/doc/docstrings/multi_select.rst" />
        <File name="multi_socket_action" src="lib/pycurl/doc/docstrings/multi_socket_action.rst" />
        <File name="multi_socket_all" src="lib/pycurl/doc/docstrings/multi_socket_all.rst" />
        <File name="pycurl_global_cleanup" src="lib/pycurl/doc/docstrings/pycurl_global_cleanup.rst" />
        <File name="pycurl_global_init" src="lib/pycurl/doc/docstrings/pycurl_global_init.rst" />
        <File name="pycurl_module" src="lib/pycurl/doc/docstrings/pycurl_module.rst" />
        <File name="pycurl_version_info" src="lib/pycurl/doc/docstrings/pycurl_version_info.rst" />
        <File name="share" src="lib/pycurl/doc/docstrings/share.rst" />
        <File name="share_close" src="lib/pycurl/doc/docstrings/share_close.rst" />
        <File name="share_setopt" src="lib/pycurl/doc/docstrings/share_setopt.rst" />
        <File name="favicon" src="lib/pycurl/doc/static/favicon.ico" />
        <File name="basicfirst" src="lib/pycurl/examples/basicfirst.py" />
        <File name="file_upload" src="lib/pycurl/examples/file_upload.py" />
        <File name="linksys" src="lib/pycurl/examples/linksys.py" />
        <File name="retriever-multi" src="lib/pycurl/examples/retriever-multi.py" />
        <File name="retriever" src="lib/pycurl/examples/retriever.py" />
        <File name="sfquery" src="lib/pycurl/examples/sfquery.py" />
        <File name="smtp" src="lib/pycurl/examples/smtp.py" />
        <File name="xmlrpc_curl" src="lib/pycurl/examples/xmlrpc_curl.py" />
        <File name="follow_redirect" src="lib/pycurl/examples/quickstart/follow_redirect.py" />
        <File name="form_post" src="lib/pycurl/examples/quickstart/form_post.py" />
        <File name="get" src="lib/pycurl/examples/quickstart/get.py" />
        <File name="get_python2" src="lib/pycurl/examples/quickstart/get_python2.py" />
        <File name="get_python3" src="lib/pycurl/examples/quickstart/get_python3.py" />
        <File name="response_headers" src="lib/pycurl/examples/quickstart/response_headers.py" />
        <File name="response_info" src="lib/pycurl/examples/quickstart/response_info.py" />
        <File name="write_file" src="lib/pycurl/examples/quickstart/write_file.py" />
        <File name="test_build_config" src="lib/pycurl/examples/tests/test_build_config.py" />
        <File name="test_gtk" src="lib/pycurl/examples/tests/test_gtk.py" />
        <File name="test_xmlrpc" src="lib/pycurl/examples/tests/test_xmlrpc.py" />
        <File name="__init__" src="lib/pycurl/python/curl/__init__.py" />
        <File name="docstrings" src="lib/pycurl/src/docstrings.c" />
        <File name="docstrings" src="lib/pycurl/src/docstrings.h" />
        <File name="easy" src="lib/pycurl/src/easy.c" />
        <File name="Makefile" src="lib/pycurl/src/Makefile" />
        <File name="module" src="lib/pycurl/src/module.c" />
        <File name="multi" src="lib/pycurl/src/multi.c" />
        <File name="oscompat" src="lib/pycurl/src/oscompat.c" />
        <File name="pycurl" src="lib/pycurl/src/pycurl.h" />
        <File name="pythoncompat" src="lib/pycurl/src/pythoncompat.c" />
        <File name="share" src="lib/pycurl/src/share.c" />
        <File name="stringcompat" src="lib/pycurl/src/stringcompat.c" />
        <File name="threadsupport" src="lib/pycurl/src/threadsupport.c" />
        <File name="__init__" src="lib/pycurl/tests/__init__.py" />
        <File name="app" src="lib/pycurl/tests/app.py" />
        <File name="appmanager" src="lib/pycurl/tests/appmanager.py" />
        <File name="certinfo_test" src="lib/pycurl/tests/certinfo_test.py" />
        <File name="curl_object_test" src="lib/pycurl/tests/curl_object_test.py" />
        <File name="debug_test" src="lib/pycurl/tests/debug_test.py" />
        <File name="default_write_function_test" src="lib/pycurl/tests/default_write_function_test.py" />
        <File name="error_constants_test" src="lib/pycurl/tests/error_constants_test.py" />
        <File name="error_test" src="lib/pycurl/tests/error_test.py" />
        <File name="ftp_test" src="lib/pycurl/tests/ftp_test.py" />
        <File name="functools_backport" src="lib/pycurl/tests/functools_backport.py" />
        <File name="getinfo_test" src="lib/pycurl/tests/getinfo_test.py" />
        <File name="global_init_test" src="lib/pycurl/tests/global_init_test.py" />
        <File name="header_function_test" src="lib/pycurl/tests/header_function_test.py" />
        <File name="header_test" src="lib/pycurl/tests/header_test.py" />
        <File name="info_constants_test" src="lib/pycurl/tests/info_constants_test.py" />
        <File name="internals_test" src="lib/pycurl/tests/internals_test.py" />
        <File name="matrix" src="lib/pycurl/tests/matrix.py" />
        <File name="memory_mgmt_test" src="lib/pycurl/tests/memory_mgmt_test.py" />
        <File name="multi_memory_mgmt_test" src="lib/pycurl/tests/multi_memory_mgmt_test.py" />
        <File name="multi_option_constants_test" src="lib/pycurl/tests/multi_option_constants_test.py" />
        <File name="multi_socket_select_test" src="lib/pycurl/tests/multi_socket_select_test.py" />
        <File name="multi_socket_test" src="lib/pycurl/tests/multi_socket_test.py" />
        <File name="multi_test" src="lib/pycurl/tests/multi_test.py" />
        <File name="multi_timer_test" src="lib/pycurl/tests/multi_timer_test.py" />
        <File name="option_constants_test" src="lib/pycurl/tests/option_constants_test.py" />
        <File name="pause_test" src="lib/pycurl/tests/pause_test.py" />
        <File name="post_test" src="lib/pycurl/tests/post_test.py" />
        <File name="procmgr" src="lib/pycurl/tests/procmgr.py" />
        <File name="protocol_constants_test" src="lib/pycurl/tests/protocol_constants_test.py" />
        <File name="pycurl_object_test" src="lib/pycurl/tests/pycurl_object_test.py" />
        <File name="read_callback_test" src="lib/pycurl/tests/read_callback_test.py" />
        <File name="readdata_test" src="lib/pycurl/tests/readdata_test.py" />
        <File name="relative_url_test" src="lib/pycurl/tests/relative_url_test.py" />
        <File name="reload_test" src="lib/pycurl/tests/reload_test.py" />
        <File name="reset_test" src="lib/pycurl/tests/reset_test.py" />
        <File name="resolve_test" src="lib/pycurl/tests/resolve_test.py" />
        <File name="runwsgi" src="lib/pycurl/tests/runwsgi.py" />
        <File name="seek_function_constants_test" src="lib/pycurl/tests/seek_function_constants_test.py" />
        <File name="seek_function_test" src="lib/pycurl/tests/seek_function_test.py" />
        <File name="setopt_lifecycle_test" src="lib/pycurl/tests/setopt_lifecycle_test.py" />
        <File name="setopt_test" src="lib/pycurl/tests/setopt_test.py" />
        <File name="setopt_unicode_test" src="lib/pycurl/tests/setopt_unicode_test.py" />
        <File name="setup_test" src="lib/pycurl/tests/setup_test.py" />
        <File name="share_test" src="lib/pycurl/tests/share_test.py" />
        <File name="socket_open_test" src="lib/pycurl/tests/socket_open_test.py" />
        <File name="unset_range_test" src="lib/pycurl/tests/unset_range_test.py" />
        <File name="user_agent_string_test" src="lib/pycurl/tests/user_agent_string_test.py" />
        <File name="util" src="lib/pycurl/tests/util.py" />
        <File name="version_comparison_test" src="lib/pycurl/tests/version_comparison_test.py" />
        <File name="version_test" src="lib/pycurl/tests/version_test.py" />
        <File name="vsftpd" src="lib/pycurl/tests/vsftpd.conf" />
        <File name="write_abort_test" src="lib/pycurl/tests/write_abort_test.py" />
        <File name="write_cb_bogus_test" src="lib/pycurl/tests/write_cb_bogus_test.py" />
        <File name="write_test" src="lib/pycurl/tests/write_test.py" />
        <File name="write_to_stringio_test" src="lib/pycurl/tests/write_to_stringio_test.py" />
        <File name="server" src="lib/pycurl/tests/certs/server.crt" />
        <File name="server" src="lib/pycurl/tests/certs/server.key" />
        <File name="test-lib" src="lib/pycurl/tests/ext/test-lib.sh" />
        <File name="test-suite" src="lib/pycurl/tests/ext/test-suite.sh" />
        <File name="curl-config-empty" src="lib/pycurl/tests/fake-curl/curl-config-empty" />
        <File name="curl-config-libs-and-static-libs" src="lib/pycurl/tests/fake-curl/curl-config-libs-and-static-libs" />
        <File name="curl-config-ssl-feature-only" src="lib/pycurl/tests/fake-curl/curl-config-ssl-feature-only" />
        <File name="curl-config-ssl-in-libs" src="lib/pycurl/tests/fake-curl/curl-config-ssl-in-libs" />
        <File name="curl-config-ssl-in-static-libs" src="lib/pycurl/tests/fake-curl/curl-config-ssl-in-static-libs" />
        <File name="form_submission" src="lib/pycurl/tests/fixtures/form_submission.txt" />
        <File name="curl-7.19.0-sslv2-2b0e09b0f98" src="lib/pycurl/tests/matrix/curl-7.19.0-sslv2-2b0e09b0f98.patch" />
        <File name="curl-7.19.0-sslv2-c66b0b32fba-modified" src="lib/pycurl/tests/matrix/curl-7.19.0-sslv2-c66b0b32fba-modified.patch" />
        <File name="python25" src="lib/pycurl/tests/matrix/python25.patch" />
        <File name="python30" src="lib/pycurl/tests/matrix/python30.patch" />
    </Resources>
    <Topics />
</Package>
